apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: kubejobs

spec:
  scaleTargetRef:
    name: worker

  minReplicaCount: 2
  maxReplicaCount: 50

  pollingInterval: 5          # safer
  cooldownPeriod: 30          # stable scaling

  advanced:
    restoreToOriginalReplicaCount: false

  triggers:
    - type: redis-streams
      metadata:
        address: rediss://master.kubejobs-redis.rw0frw.aps1.cache.amazonaws.com:6379

        stream: jobs_stream
        consumerGroup: workers

        lagThreshold: "100"
        activationLagThreshold: "10"