apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-auth
  namespace: kubejobs
spec:
  secretTargetRef:
  - parameter: password
    name: redis-secret
    key: password

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: kubejobs
spec:
  scaleTargetRef:
    name: worker

  minReplicaCount: 2
  maxReplicaCount: 50

  pollingInterval: 2          # fast reaction
  cooldownPeriod: 15          # avoid aggressive scale down

  advanced:
    restoreToOriginalReplicaCount: false

  triggers:
  - type: redis-streams
    metadata:
      address: redis-0.redis.kubejobs.svc.cluster.local:6379
      stream: jobs_stream
      consumerGroup: workers

      lagThreshold: "100"

      activationLagThreshold: "10"

    authenticationRef:
      name: redis-auth