apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: kubejobs
  labels:
    app: redis

spec:
  serviceName: redis
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      terminationGracePeriodSeconds: 20

      containers:
        - name: redis
          image: redis:7
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 6379

          command: ["sh", "-c"]
          args:
            - |
              redis-server \
              --appendonly yes \
              --appendfsync everysec \
              --requirepass "$REDIS_PASSWORD"

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

          volumeMounts:
            - name: redis-data
              mountPath: /data

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          securityContext:
            allowPrivilegeEscalation: false

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi