apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubejobs-quota
  namespace: kubejobs
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "30"