apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubejobs-quota
  namespace: kubejobs

spec:
  hard:
    requests.cpu: "4"
    requests.memory: "5Gi"

    limits.cpu: "8"
    limits.memory: "8Gi"

    pods: "50"

    services: "10"
    configmaps: "30"
    secrets: "30"

    persistentvolumeclaims: "5"