apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubejobs-sa
  namespace: kubejobs

  labels:
    app.kubernetes.io/name: kubejobs
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: job-system

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::409837635702:role/kubejobs-app-irsa-role

    eks.amazonaws.com/sts-regional-endpoints: "true"

automountServiceAccountToken: true