name: KubeJobs Production Deploy

on:
  push:
    branches: [ "main", "aws-prod-latest" ]
    tags:
      - "v*"
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: kubejobs
  NAMESPACE: kubejobs
  ECR_REPO: 409837635702.dkr.ecr.ap-south-1.amazonaws.com/kubejobs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify AWS
      run: aws sts get-caller-identity

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_REPO

    - name: Build & Push Image
      run: |
        set -e

        docker build -f deployments/docker/Dockerfile -t kubejobs:${{ github.sha }} .

        docker tag kubejobs:${{ github.sha }} $ECR_REPO:${{ github.sha }}
        docker tag kubejobs:${{ github.sha }} $ECR_REPO:latest

        docker push $ECR_REPO:${{ github.sha }}
        docker push $ECR_REPO:latest

    - name: Setup kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

    - name: Verify cluster access
      run: kubectl get nodes

    - name: Apply base configs
      run: |
        kubectl apply -f deployments/kubernetes/namespace.yaml
        kubectl apply -f deployments/kubernetes/serviceaccount.yaml
        kubectl apply -f deployments/kubernetes/limit-range.yaml
        kubectl apply -f deployments/kubernetes/resource-quota.yaml
        kubectl apply -f deployments/kubernetes/network-policy.yaml

    # ---------------- SECRET ----------------
    - name: Apply secret
      run: |
        kubectl create secret generic app-config \
          --from-literal=REDIS_ADDR=rediss://master.kubejobs-redis.rw0frw.aps1.cache.amazonaws.com:6379 \
          -n $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply workloads
      run: |
        kubectl apply -f deployments/kubernetes/api-deployment.yaml
        kubectl apply -f deployments/kubernetes/worker-deployment.yaml
        kubectl apply -f deployments/kubernetes/service.yaml
        kubectl apply -f deployments/kubernetes/keda-scaledobject.yaml

    - name: Update image (atomic)
      run: |
        kubectl set image deployment/api api=$ECR_REPO:${{ github.sha }} -n $NAMESPACE
        kubectl set image deployment/worker worker=$ECR_REPO:${{ github.sha }} -n $NAMESPACE

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/api -n $NAMESPACE --timeout=180s
        kubectl rollout status deployment/worker -n $NAMESPACE --timeout=180s

    - name: Verify pods
      run: |
        kubectl get pods -n $NAMESPACE -o wide

    - name: Get LoadBalancer URL
      run: |
        echo "Waiting for LoadBalancer..."

        for i in {1..40}; do
          HOST=$(kubectl get svc api -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          if [ -n "$HOST" ]; then
            echo "API_URL=http://$HOST" >> $GITHUB_ENV
            echo "API URL: $HOST"
            exit 0
          fi

          sleep 10
        done

        echo "LoadBalancer not ready"
        kubectl get svc -n $NAMESPACE
        exit 1

    - name: Health check
      run: |
        curl -f $API_URL/health

    - name: Run integration test
      run: |
        chmod +x test.sh
        BASE_URL=$API_URL ./test.sh || true

    - name: Debug (on failure)
      if: failure()
      run: |
        echo "==== PODS ===="
        kubectl get pods -n $NAMESPACE

        echo "==== DESCRIBE ===="
        kubectl describe pods -n $NAMESPACE

        echo "==== LOGS ===="
        kubectl logs -l app=api -n $NAMESPACE --tail=100 || true
        kubectl logs -l app=worker -n $NAMESPACE --tail=100 || true